
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import sys
sys.path.append('/lib/db/models')
from db.models import Base, Recipe, Ingredient,FoodAssociation

def seed_database():

    regions = []
    ingredients = session.query(Ingredient).all()
    recipes = session.query(Recipe).all()

    associations = []
    regions_data = [
        {"name": "Italy"},
        {"name": "France"},
        {"name": "Spain"},
        {"name": "Greece"},
        {"name": "Turkey"},
        {"name": "Portugal"},
        {"name": "Mexico"},
        {"name": "Brazil"},
        {"name": "Argentina"},
        {"name": "Peru"},
        {"name": "Japan"},
        {"name": "China"},
        {"name": "Thailand"},
        {"name": "India"},
        {"name": "South Korea"},
        {"name": "Vietnam"},
        {"name": "Malaysia"},
        {"name": "Indonesia"},
        {"name": "Middle Eastern"},
        {"name": "Morocco"},
        {"name": "Ethiopia"},
        {"name": "Nigeria"},
        {"name": "South Africa"},
        {"name": "United States"},
        {"name": "Canada"},
        {"name": "Australia"},
        {"name": "New Zealand"},
        {"name": "Russia"},
        {"name": "Scandinavia"},
        {"name": "Eastern Europe"},
    ]
    ingredients_data = [
        {"name": "Olive Oil"},
        {"name": "Tomatoes"},
        {"name": "Basil"},
        {"name": "Garlic"},
        {"name": "Parmesan Cheese"},
        {"name": "Mozzarella Cheese"},
        {"name": "Pasta"},
        {"name": "Prociutto"},
        {"name": "Rice"},
        {"name": "Balsamic Vinegar"},
        {"name": "Butter"},
        {"name": "Baguette"},
        {"name": "Wine"},
        {"name": "Thyme"},
        {"name": "Tarragon"},
        {"name": "Dijon Mustard"},
        {"name": "Brie Cheese"},
        {"name": "Croissant"},
        {"name": "Escargot"},
        {"name": "Champagne"},
        {"name": "Paprika"},
        {"name": "Saffron"},
        {"name": "Chorizo"},
        {"name": "Almonds"},
        {"name": "Sherry Vinegar"},
        {"name": "Manchego cheese"},
        {"name": "Olives"},
        {"name": "Anchovies"},
        {"name": "Feta Cheese"},
        {"name": "Oregano"},
        {"name": "Lemon"},
        {"name": "Yogurt"},
        {"name": "Eggplant"},
        {"name": "Spinach"},
        {"name": "Lamb"},
        {"name": "Yogurt"},
        {"name": "Mint"},
        {"name": "Bulgur"},
        {"name": "Sumac"},
        {"name": "Cumin"},
        {"name": "Pomegranate"},
        {"name": "Codfish"},
        {"name": "Sausage"},
        {"name": "Cilantro"},
        {"name": "Bacalhau"},
        {"name": "Sardines"},
        {"name": "Tortillas"},
        {"name": "Beans"},
        {"name": "Lime"},
        {"name": "Jalapeno Peppers"},
        {"name": "Chiles"},
        {"name": "Tomatillos"},
        {"name": "Queso Fresco"},
        {"name": "Masa"},
        {"name": "Cassava"},
        {"name": "Coconut Milk"},
        {"name": "Plantains"},
        {"name": "Acai"},
        {"name": "Malbec Wine"},
        {"name": "Potatoes"},
        {"name": "Aji peppers"},
        {"name": "Onions"},
        {"name": "Bell Peppers"},
        {"name": "Soy sauce"},
        {"name": "Nori"},
        {"name": "Wasabi"},
        {"name": "Ginger"},
        {"name": "Miso"},
        {"name": "Mirin"},
        {"name": "Matcha"},
        {"name": "Dashi"},
        {"name": "Fish"},
        {"name": "Rice Vinegar"},
        {"name": "Sichuan Peppercorns"},
        {"name": "Bok Choy"},
        {"name": "Tofu"},
        {"name": "Oyster Sauce"},
        {"name": "Lemongrass"},
        {"name": "Thai Basil"},
        {"name": "Galangal"},
        {"name": "Fish Sauce"},
        {"name": "Red curry paste"},
        {"name": "Green curry paste"},
        {"name": "Peanuts"},
        {"name": "Tamarind"},
        {"name": "Ghee"},
        {"name": "Lentils"},
        {"name": "Paneer"},
        {"name": "Naan"},
        {"name": "Masala Chai"},
        {"name": "Saffron"},
        {"name": "Gochujang"},
        {"name": "Kimchi"},
        {"name": "Sesame Oil"},
        {"name": "Bulgogi"},
        {"name": "Rice Cakes"},
        {"name": "Kimbap"},
        {"name": "Doenjang"},
        {"name": "Rice Paper"},
        {"name": "Beef"},
        {"name": "Hoisin Sauce"},
        {"name": "Belacan"},
        {"name": "Curry Leaves"},
        {"name": "Pandan leaves"},
        {"name": "Satay"},
        {"name": "Rendang"},
        {"name": "Kecap Manis"},
        {"name": "Sambal"},
        {"name": "Tempeh"},
        {"name": "Bumbu"},
        {"name": "Hummus"},
        {"name": "Falafel"},
        {"name": "Tahini"},
        {"name": "Pita"},
        {"name": "Za'atar"},
        {"name": "Dates"},
        {"name": "Couscous"},
        {"name": "Harissa"},
        {"name": "Injera"},
        {"name": "Berbere"},
        {"name": "Egusi"},
        {"name": "Bitterleaf"},
        {"name": "Biltong"},
        {"name": "Bobotie"},
        {"name": "Boerewors"},
        {"name": "Chutney"},
        {"name": "Vetkoek"},
        {"name": "Amarula"},
        {"name": "Ground Beef"},
        {"name": "Bacon"},
        {"name": "Corn"},
        {"name": "Barbecue Sauce"},
        {"name": "Hot Dogs"},
        {"name": "Peanut Butter"},
        {"name": "Maple Syrup"},
        {"name": "Peameal Bacon"},
        {"name": "Bannock"},
        {"name": "Elk"},
        {"name": "Deer"},
        {"name": "Pork"},
        {"name": "Ketchup"},
        {"name": "Vegemite"},
        {"name": "Egg"},
        {"name": "Ham"},
        {"name": "Black Pepper"},
        {"name": "Vegemite"},
    ]
    recipes_data = [
    # Italy
    {"name": "Spaghetti Carbonara",
    "description": "A classic Roman dish featuring pasta tossed with crispy bacon, eggs, Pecorino Romano cheese, and black pepper.",
    "region": "Italy"},
    {"name": "Margherita Pizza",
    "description": "A simple yet delicious pizza topped with tomato sauce, mozzarella cheese, fresh tomatoes, and basil leaves.",
    "region": "Italy"},
    {"name": "Risotto Milanese",
    "description": "Creamy saffron-infused rice dish made with Arborio rice, onions, and Parmesan cheese.",
    "region": "Italy"},
    {"name": "Osso Buco",
    "description": "Braised veal shanks cooked with tomatoes, white wine, and aromatic vegetables, served with gremolata.",
    "region": "Italy"},
    {"name": "Pesto Genovese",
    "description": "Fresh basil, pine nuts, garlic, Parmesan cheese, and olive oil blended into a flavorful pesto sauce for pasta or bruschetta.",
    "region": "Italy"},
    {"name": "Caprese Stuffed Chicken",
    "description": "Chicken breasts stuffed with mozzarella cheese, tomatoes, and basil, baked to perfection.",
    "region": "Italy"},
    {"name": "Tiramisu",
    "description": "A popular dessert made with layers of coffee-soaked ladyfingers, mascarpone cheese, cocoa powder, and chocolate.",
    "region": "Italy"},
    {"name": "Eggplant Parmesan",
    "description": "Slices of breaded and fried eggplant layered with marinara sauce and melted mozzarella cheese.",
    "region": "Italy"},
    {"name": "Fettuccine Alfredo",
    "description": "Creamy pasta dish made with fettuccine noodles, butter, heavy cream, and Parmesan cheese.",
    "region": "Italy"},
    {"name": "Amatriciana Sauce",
    "description": "A savory tomato-based sauce with pancetta or guanciale, onions, and Pecorino cheese, often served with bucatini pasta.",
    "region": "Italy"},

    # France
    {"name": "Quiche Lorraine",
    "description": "Savory tart filled with a custard mixture of eggs, cream, bacon, and Gruyère cheese.",
    "region": "France"},
    {"name": "Bouillabaisse",
    "description": "A Provençal fish stew made with various fish, shellfish, tomatoes, saffron, and herbs.",
    "region": "France"},
    {"name": "Cassoulet",
    "description": "Hearty stew featuring white beans, sausage, duck, and sometimes pork, slow-cooked to perfection.",
    "region": "France"},
    {"name": "Croque Monsieur",
    "description": "Grilled ham and cheese sandwich topped with béchamel sauce and more cheese, often served with a fried egg.",
    "region": "France"},
    {"name": "Ratatouille",
    "description": "A colorful vegetable medley dish made with eggplant, zucchini, bell peppers, onions, and tomatoes.",
    "region": "France"},
    {"name": "Coq au Vin Blanc",
    "description": "A variation of coq au vin, made with white wine, mushrooms, and chicken braised until tender.",
    "region": "France"},
    {"name": "Tarte Tatin",
    "description": "Upside-down caramelized apple tart, often served with a dollop of crème fraîche.",
    "region": "France"},
    {"name": "Escargot in Garlic Butter",
    "description": "Snails cooked in garlic herb butter, served in their shells with a special snail fork.",
    "region": "France"},
    {"name": "Duck à l'Orange",
    "description": "Roasted duck served with a tangy orange sauce, a classic French dish.",
    "region": "France"},
    {"name": "Salade Niçoise",
    "description": "A composed salad featuring lettuce, tuna, hard-boiled eggs, olives, green beans, and anchovies, often dressed with vinaigrette.",
    "region": "France"},

    # Spain
    {"name": "Gazpacho",
    "description": "Chilled tomato-based soup made with fresh vegetables like cucumbers, bell peppers, and onions.",
    "region": "Spain"},
    {"name": "Patatas Bravas",
    "description": "Crispy fried potato cubes served with spicy tomato sauce and aioli.",
    "region": "Spain"},
    {"name": "Tortilla Española",
    "description": "A Spanish omelette made with eggs, potatoes, and onions, often served as tapas.",
    "region": "Spain"},
    {"name": "Gambas al Ajillo",
    "description": "Sautéed shrimp cooked with garlic, red pepper flakes, and olive oil, a popular tapas dish.",
    "region": "Spain"},
    {"name": "Paella Valenciana",
    "description": "A saffron-infused rice dish cooked with rabbit, chicken, vegetables, and sometimes snails.",
    "region": "Spain"},
    {"name": "Churros",
    "description": "Fried dough pastries dusted with sugar, often served with a cup of hot chocolate for dipping.",
    "region": "Spain"},
    {"name": "Pulpo a la Gallega",
    "description": "Galician-style octopus dish featuring tender octopus slices, paprika, and olive oil.",
    "region": "Spain"},
    {"name": "Crema Catalana",
    "description": "A creamy custard dessert topped with a layer of caramelized sugar, similar to crème brûlée.",
    "region": "Spain"},
    {"name": "Ensalada Mixta",
    "description": "Mixed salad made with lettuce, tomatoes, olives, hard-boiled eggs, and tuna, drizzled with olive oil.",
    "region": "Spain"},
    {"name": "Cochinillo Asado",
    "description": "Roasted suckling pig, a traditional Spanish dish often served during festive occasions.",
    "region": "Spain"},

    # Greece
    {"name": "Moussaka",
    "description": "Layers of eggplant, potatoes, and spiced ground meat topped with creamy béchamel sauce, baked to perfection.",
    "region": "Greece"},
    {"name": "Souvlaki",
    "description": "Grilled skewers of marinated meat (usually lamb or chicken) served with pita bread and tzatziki sauce.",
    "region": "Greece"},
    {"name": "Spanakopita",
    "description": "Flaky phyllo pastry filled with a mixture of spinach, feta cheese, onions, and herbs.",
    "region": "Greece"},
    {"name": "Dolmas",
    "description": "Grape leaves stuffed with a flavorful mixture of rice, herbs, and sometimes ground meat.",
    "region": "Greece"},
    {"name": "Greek Salad (Horiatiki)",
    "description": "Traditional salad featuring tomatoes, cucumbers, red onions, Kalamata olives, and feta cheese.",
    "region": "Greece"},
    {"name": "Tzatziki",
    "description": "Creamy yogurt dip made with cucumber, garlic, and dill, often served with pita bread or as a condiment.",
    "region": "Greece"},
    {"name": "Avgolemono Soup",
    "description": "Chicken and rice soup thickened with a mixture of eggs and lemon juice, creating a tangy and creamy texture.",
    "region": "Greece"},
    {"name": "Koulourakia",
    "description": "Greek butter cookies often flavored with vanilla or citrus, shaped into various twists and knots.",
    "region": "Greece"},
    {"name": "Pastitsio",
    "description": "Baked pasta dish made with tubular pasta, spiced meat sauce, and a creamy béchamel topping.",
    "region": "Greece"},
    {"name": "Galaktoboureko",
    "description": "A dessert made with layers of phyllo pastry and a semolina custard filling, baked until golden and then soaked in a sugar syrup.",
    "region": "Greece"},

    # Turkey
    {"name": "Iskender Kebab",
    "description": "Sliced lamb or beef doner served over pita bread, topped with tomato sauce and yogurt.",
    "region": "Turkey"},
    {"name": "Meze Platter",
    "description": "A selection of small dishes like hummus, baba ghanoush, olives, and stuffed grape leaves, served as appetizers.",
    "region": "Turkey"},
    {"name": "Lahmacun",
    "description": "Turkish flatbread topped with spiced minced meat, onions, and herbs, often rolled and eaten like a wrap.",
    "region": "Turkey"},
    {"name": "Simit",
    "description": "Sesame-covered bread rings, a popular street food often enjoyed with tea or as a quick snack.",
    "region": "Turkey"},
    {"name": "Karnıyarık",
    "description": "Stuffed eggplant dish filled with spiced ground meat and vegetables, usually served with rice.",
    "region": "Turkey"},
    {"name": "Manti",
    "description": "Tiny dumplings filled with spiced meat, often served with yogurt and drizzled with melted butter and paprika.",
    "region": "Turkey"},
    {"name": "Pide",
    "description": "Turkish boat-shaped flatbread topped with various ingredients like cheese, meat, and vegetables.",
    "region": "Turkey"},
    {"name": "Çılbır",
    "description": "Poached eggs served over yogurt, drizzled with chili-infused butter and sprinkled with red pepper flakes.",
    "region": "Turkey"},
    {"name": "Baklava",
    "description": "Sweet dessert made with layers of phyllo pastry, chopped nuts, and honey syrup.",
    "region": "Turkey"},
    {"name": "Turkish Tea",
    "description": "Strong black tea, often brewed in a special double teapot and served in small glasses.",
    "region": "Turkey"},

    # Portugal
    {"name": "Bacalhau à Gomes de Sá",
    "description": "A traditional Portuguese codfish dish made with layers of codfish, potatoes, onions, and olives.",
    "region": "Portugal"},
    {"name": "Portuguese Kale Soup (Caldo Verde)",
    "description": "Hearty soup made with kale, potatoes, sausage, and often garnished with olive oil.",
    "region": "Portugal"},
    {"name": "Francesinha",
    "description": "A hearty sandwich featuring layers of cured meats and sausage, covered in melted cheese and a spicy tomato-based sauce.",
    "region": "Portugal"},
    {"name": "Pastel de Nata",
    "description": "Flaky custard tart made with a creamy egg filling, cinnamon, and a hint of lemon zest.",
    "region": "Portugal"},
    {"name": "Arroz de Pato",
    "description": "Portuguese duck rice casserole made with duck meat, rice, chorizo, and often baked until crispy.",
    "region": "Portugal"},
    {"name": "Chouriço Assado",
    "description": "Grilled Portuguese sausage often served with crusty bread and olives.",
    "region": "Portugal"},
    {"name": "Ameijoas à Bulhão Pato",
    "description": "Clams cooked with garlic, olive oil, and white wine, served with a sprinkle of fresh cilantro.",
    "region": "Portugal"},
    {"name": "Salada de Polvo",
    "description": "Octopus salad made with tender boiled octopus, onions, bell peppers, and olive oil.",
    "region": "Portugal"},
    {"name": "Bifana",
    "description": "Marinated and sautéed pork slices served in a bread roll, often enjoyed as a quick snack.",
    "region": "Portugal"},
    {"name": "Peri-Peri Chicken",
    "description": "Grilled or roasted chicken marinated in a spicy peri-peri sauce made from African bird's eye chili peppers.",
    "region": "Portugal"},

    # Mexico
    {"name": "Chiles Rellenos",
    "description": "Poblano peppers stuffed with cheese, meat, or beans, battered and fried, often served with tomato sauce.",
    "region": "Mexico"},
    {"name": "Enchiladas",
    "description": "Rolled tortillas filled with meat, cheese, or beans, topped with chili sauce and melted cheese.",
    "region": "Mexico"},
    {"name": "Tamales",
    "description": "Steamed masa dough filled with various ingredients like meat, cheese, and vegetables, often wrapped in corn husks.",
    "region": "Mexico"},
    {"name": "Guacamole",
    "description": "Creamy avocado dip made with ripe avocados, tomatoes, onions, cilantro, lime juice, and spices.",
    "region": "Mexico"},
    {"name": "Chilaquiles",
    "description": "Fried tortilla chips smothered in red or green salsa, often topped with cheese, sour cream, and eggs.",
    "region": "Mexico"},
    {"name": "Pozole",
    "description": "Hearty hominy soup made with pork or chicken, topped with shredded lettuce, radishes, onions, and lime.",
    "region": "Mexico"},
    {"name": "Carnitas",
    "description": "Slow-cooked, tender pork often used as a filling for tacos, burritos, or tortas.",
    "region": "Mexico"},
    {"name": "Sopes",
    "description": "Thick cornmeal dough patties topped with beans, meat, lettuce, cheese, and salsa.",
    "region": "Mexico"},
    {"name": "Tres Leches Cake",
    "description": "A moist sponge cake soaked in a mixture of three types of milk (evaporated milk, condensed milk, and heavy cream), often topped with whipped cream and fruit.",
    "region": "Mexico"},
    {"name": "Michelada",
    "description": "A refreshing cocktail made with beer, lime juice, hot sauce, and assorted seasonings, served over ice in a salt-rimmed glass.",
    "region": "Mexico"},

    # Brazil
    {"name": "Feijão Tropeiro",
    "description": "A hearty dish made with beans, bacon, sausage, eggs, and cassava flour, often served with rice.",
    "region": "Brazil"},
    {"name": "Moqueca de Peixe",
    "description": "A flavorful fish stew made with coconut milk, tomatoes, onions, peppers, and dendê (palm) oil.",
    "region": "Brazil"},
    {"name": "Acarajé",
    "description": "Deep-fried black-eyed pea fritters often filled with spicy shrimp and accompanied by vatapá (spicy coconut sauce).",
    "region": "Brazil"},
    {"name": "Pão de Queijo",
    "description": "Cheesy bread rolls made with tapioca flour and grated cheese, a popular snack in Brazil.",
    "region": "Brazil"},
    {"name": "Caipirinha",
    "description": "Brazil's national cocktail made with cachaça (sugarcane rum), lime, and sugar, served over ice.",
    "region": "Brazil"},
    {"name": "Churrasco",
    "description": "Brazilian barbecue featuring various cuts of meat, often served with farofa (toasted cassava flour) and vinaigrette.",
    "region": "Brazil"},
    {"name": "Brigadeiro",
    "description": "Sweet confection made with condensed milk, cocoa powder, butter, and chocolate sprinkles.",
    "region": "Brazil"},
    {"name": "Vatapá",
    "description": "A creamy dish made from bread, shrimp, coconut milk, and ground nuts, often served with rice or acarajé.",
    "region": "Brazil"},
    {"name": "Quindim",
    "description": "A custard-like dessert made with coconut, sugar, butter, and egg yolks, baked until golden.",
    "region": "Brazil"},
    {"name": "Canjica",
    "description": "A warm dessert made with corn kernels, milk, sugar, and often spiced with cinnamon and cloves.",
    "region": "Brazil"},

    # Argentina
    {"name": "Matambre a la Pizza",
    "description": "A grilled flank steak topped with tomato sauce, melted cheese, and herbs, resembling a pizza.",
    "region": "Argentina"},
    {"name": "Empanadas de Carne",
    "description": "Traditional Argentine beef empanadas made with a flavorful filling of ground beef, onions, olives, and hard-boiled eggs.",
    "region": "Argentina"},
    {"name": "Chimichurri Grilled Steak",
    "description": "Grilled steak marinated in chimichurri sauce made with parsley, garlic, red pepper flakes, vinegar, and olive oil.",
    "region": "Argentina"},
    {"name": "Milanesa de Pollo",
    "description": "Breaded and fried chicken cutlet, often served with a squeeze of lemon and a side of mashed potatoes.",
    "region": "Argentina"},
    {"name": "Provoleta",
    "description": "Grilled provolone cheese topped with oregano and red pepper flakes, often served as an appetizer.",
    "region": "Argentina"},
    {"name": "Asado",
    "description": "Traditional Argentine barbecue featuring various cuts of meat slow-cooked over an open flame or charcoal.",
    "region": "Argentina"},
    {"name": "Dulce de Leche",
    "description": "A sweet caramel-like spread made from condensed milk, often used in desserts and pastries.",
    "region": "Argentina"},
    {"name": "Locro",
    "description": "A hearty stew made with white corn, potatoes, beans, sausage, and sometimes tripe, often enjoyed during colder months.",
    "region": "Argentina"},
    {"name": "Pastelitos",
    "description": "Sweet fried pastries filled with quince paste, sweet potato, or dulce de leche, often dusted with powdered sugar.",
    "region": "Argentina"},
    {"name": "Helado",
    "description": "Argentine-style ice cream known for its creamy texture and variety of flavors, a popular treat in Argentina.",
    "region": "Argentina"},

    # Peru
    {"name": "Lomo Saltado",
    "description": "A stir-fry dish made with marinated beef, onions, tomatoes, and French fries, often served with rice.",
    "region": "Peru"},
    {"name": "Anticuchos",
    "description": "Grilled skewers of marinated meat, often made from beef heart, and served with a spicy sauce.",
    "region": "Peru"},
    {"name": "Causa Rellena",
    "description": "Layered potato dish with a filling of chicken, tuna, or vegetables, often garnished with avocado and olives.",
    "region": "Peru"},
    {"name": "Papa a la Huancaina",
    "description": "Boiled yellow potatoes served with a spicy cheese sauce made from aji amarillo peppers.",
    "region": "Peru"},
    {"name": "Ceviche de Pescado",
    "description": "Fresh fish marinated in lime juice, mixed with red onions, cilantro, and Aji peppers.",
    "region": "Peru"},
    {"name": "Ají de Gallina",
    "description": "Shredded chicken cooked in a creamy sauce made with Aji amarillo peppers, cheese, and milk, often served with rice and boiled potatoes.",
    "region": "Peru"},
    {"name": "Rocoto Relleno",
    "description": "Stuffed spicy rocoto peppers, usually filled with ground meat, vegetables, and cheese.",
    "region": "Peru"},
    {"name": "Cuy al Horno",
    "description": "Roasted guinea pig, a traditional Peruvian dish often enjoyed during festive occasions.",
    "region": "Peru"},
    {"name": "Pisco Sour",
    "description": "A popular cocktail made with pisco (grape brandy), lime juice, simple syrup, egg white, and bitters.",
    "region": "Peru"},
    {"name": "Suspiro Limeño",
    "description": "A sweet dessert made with layers of dulce de leche and a creamy caramel-like topping, often sprinkled with cinnamon.",
    "region": "Peru"},
    
    # Japan
    {"name": "Sushi",
    "description": "A traditional Japanese dish featuring vinegared rice, seafood, and vegetables, often served with soy sauce and wasabi.",
    "region": "Japan"},
    {"name": "Ramen",
    "description": "A flavorful noodle soup with various toppings like sliced pork, eggs, and green onions.",
    "region": "Japan"},
    {"name": "Tempura",
    "description": "Lightly battered and deep-fried seafood, vegetables, or other ingredients.",
    "region": "Japan"},
    {"name": "Teriyaki Chicken",
    "description": "Grilled or broiled chicken marinated in teriyaki sauce, often served with rice and vegetables.",
    "region": "Japan"},
    {"name": "Miso Soup",
    "description": "A Japanese soup made with miso paste, tofu, seaweed, and green onions.",
    "region": "Japan"},
    {"name": "Gyoza",
    "description": "Pan-fried Japanese dumplings filled with ground meat and vegetables.",
    "region": "Japan"},
    {"name": "Yakitori",
    "description": "Skewered and grilled chicken pieces, often seasoned with tare sauce.",
    "region": "Japan"},
    {"name": "Chirashi Sushi",
    "description": "A bowl of sushi rice topped with a variety of sashimi and other ingredients.",
    "region": "Japan"},
    {"name": "Okonomiyaki",
    "description": "A savory Japanese pancake made with cabbage, meat or seafood, and various toppings.",
    "region": "Japan"},
    {"name": "Tonkatsu",
    "description": "Breaded and deep-fried pork cutlet, often served with cabbage and tonkatsu sauce.",
    "region": "Japan"},

    # China
    {"name": "Kung Pao Chicken",
    "description": "A spicy stir-fry dish made with diced chicken, peanuts, and vegetables in a savory sauce.",
    "region": "China"},
    {"name": "Dim Sum",
    "description": "Assorted bite-sized dishes often served in steamer baskets, including dumplings, buns, and rolls.",
    "region": "China"},
    {"name": "Peking Duck",
    "description": "A famous Chinese dish featuring roasted duck with crispy skin, often served with pancakes and hoisin sauce.",
    "region": "China"},
    {"name": "Mapo Tofu",
    "description": "A Sichuan dish made with tofu and minced meat in a spicy chili bean sauce.",
    "region": "China"},
    {"name": "Chow Mein",
    "description": "Stir-fried noodles with vegetables, meat, and sometimes seafood.",
    "region": "China"},
    {"name": "Ma Po Eggplant",
    "description": "Stir-fried eggplant cooked in a spicy and flavorful sauce.",
    "region": "China"},
    {"name": "Hot Pot",
    "description": "A communal meal where diners cook a variety of ingredients in a simmering pot of broth.",
    "region": "China"},
    {"name": "Spring Rolls",
    "description": "Crispy fried or fresh rolls filled with vegetables, meat, and sometimes shrimp.",
    "region": "China"},
    {"name": "Kung Pao Shrimp",
    "description": "Similar to Kung Pao Chicken, but with shrimp as the main protein.",
    "region": "China"},
    {"name": "Zhajiangmian",
    "description": "Chinese noodles topped with a mixture of ground meat and fermented soybean paste.",
    "region": "China"},

    # Thailand
    {"name": "Green Curry",
    "description": "A Thai curry made with a flavorful paste, coconut milk, and vegetables, often served with rice.",
    "region": "Thailand"},
    {"name": "Tom Yum Goong",
    "description": "A hot and sour Thai soup made with shrimp, mushrooms, lemongrass, and lime juice.",
    "region": "Thailand"},
    {"name": "Pad Thai",
    "description": "Stir-fried rice noodles with shrimp, tofu, eggs, and bean sprouts, often served with crushed peanuts and lime.",
    "region": "Thailand"},
    {"name": "Som Tum",
    "description": "A refreshing Thai salad made with green papaya, chili, lime, fish sauce, and peanuts.",
    "region": "Thailand"},
    {"name": "Massaman Curry",
    "description": "A rich and fragrant Thai curry made with potatoes, meat, and roasted spices.",
    "region": "Thailand"},
    {"name": "Tom Kha Gai",
    "description": "A coconut milk-based soup with chicken, galangal, kaffir lime leaves, and Thai chilies.",
    "region": "Thailand"},
    {"name": "Panang Curry",
    "description": "A creamy and nutty Thai curry made with meat and a thick red curry paste.",
    "region": "Thailand"},
    {"name": "Khao Pad",
    "description": "Thai fried rice with a combination of meats, vegetables, and aromatics.",
    "region": "Thailand"},
    {"name": "Red Curry",
    "description": "Another popular Thai curry made with red chili paste, coconut milk, and various proteins.",
    "region": "Thailand"},
    {"name": "Pad Krapow Moo",
    "description": "Stir-fried minced pork with Thai holy basil, garlic, and chilies, often served over rice with a fried egg.",
    "region": "Thailand"},

    # India
    {"name": "Chicken Tikka Masala",
    "description": "Tender chicken pieces cooked in a creamy tomato-based sauce with Indian spices.",
    "region": "India"},
    {"name": "Paneer Tikka",
    "description": "Cubes of paneer (Indian cheese) marinated and grilled with spices and vegetables.",
    "region": "India"},
    {"name": "Biryani",
    "description": "Fragrant rice dish cooked with spices, meat, and/or vegetables.",
    "region": "India"},
    {"name": "Aloo Gobi",
    "description": "A vegetarian Indian dish made with potatoes and cauliflower cooked in spices.",
    "region": "India"},
    {"name": "Palak Paneer",
    "description": "Paneer (Indian cheese) cooked in a spinach-based sauce with spices.",
    "region": "India"},
    {"name": "Chana Masala",
    "description": "A spicy chickpea dish cooked in a tomato-based sauce with Indian spices.",
    "region": "India"},
    {"name": "Tandoori Chicken",
    "description": "Chicken marinated in yogurt and spices, then roasted in a tandoor (clay oven).",
    "region": "India"},
    {"name": "Masala Dosa",
    "description": "A South Indian dish consisting of a thin crispy crepe filled with spiced potatoes.",
    "region": "India"},
    {"name": "Rogan Josh",
    "description": "A flavorful Kashmiri curry made with tender pieces of meat and aromatic spices.",
    "region": "India"},
    {"name": "Gulab Jamun",
    "description": "Indian dessert made from fried milk dough balls soaked in a sugary syrup.",
    "region": "India"},

    # South Korea
    {"name": "Bibimbap",
    "description": "A Korean rice dish topped with assorted vegetables, meat, and a fried egg, often served with gochujang sauce.",
    "region": "South Korea"},
    {"name": "Kimchi Jjigae",
    "description": "A spicy Korean stew made with kimchi, tofu, vegetables, and often pork.",
    "region": "South Korea"},
    {"name": "Japchae",
    "description": "A Korean stir-fried noodle dish made with sweet potato glass noodles, vegetables, and sometimes meat.",
    "region": "South Korea"},
    {"name": "Bulgogi",
    "description": "Marinated and grilled slices of beef or pork, often served with rice and lettuce wraps.",
    "region": "South Korea"},
    {"name": "Tteokbokki",
    "description": "Spicy stir-fried rice cakes cooked in a flavorful gochujang-based sauce.",
    "region": "South Korea"},
    {"name": "Samgyeopsal",
    "description": "Korean grilled pork belly often enjoyed with various accompaniments.",
    "region": "South Korea"},
    {"name": "Haemul Pajeon",
    "description": "Korean seafood pancake made with green onions and a variety of seafood.",
    "region": "South Korea"},
    {"name": "Galbitang",
    "description": "Clear Korean soup made with beef short ribs and aromatic vegetables.",
    "region": "South Korea"},
    {"name": "Bossam",
    "description": "Korean dish featuring boiled pork belly slices wrapped in lettuce with garlic and ssamjang sauce.",
    "region": "South Korea"},
    {"name": "Naengmyeon",
    "description": "Korean cold noodle dish served in a tangy broth, often topped with sliced beef and vegetables.",
    "region": "South Korea"},

    # Vietnam
    {"name": "Pho",
    "description": "A Vietnamese noodle soup made with flavorful broth, rice noodles, herbs, and choice of meat.",
    "region": "Vietnam"},
    {"name": "Banh Mi",
    "description": "A Vietnamese sandwich featuring a baguette filled with various ingredients like grilled meats, vegetables, and condiments.",
    "region": "Vietnam"},
    {"name": "Goi Cuon",
    "description": "Vietnamese spring rolls filled with shrimp, herbs, pork, rice vermicelli, and other ingredients.",
    "region": "Vietnam"},
    {"name": "Bun Cha",
    "description": "A Vietnamese dish featuring grilled pork patties and vermicelli noodles served with herbs and nuoc cham sauce.",
    "region": "Vietnam"},
    {"name": "Ca Kho To",
    "description": "Vietnamese caramelized fish cooked in a clay pot with a sweet and savory sauce.",
    "region": "Vietnam"},
    {"name": "Com Ga",
    "description": "Vietnamese dish of shredded chicken with rice and various accompaniments.",
    "region": "Vietnam"},
    {"name": "Bun Thit Nuong",
    "description": "Vietnamese dish with grilled pork served over vermicelli noodles and fresh herbs.",
    "region": "Vietnam"},
    {"name": "Canh Chua",
    "description": "Vietnamese sour soup often made with fish, tomatoes, and various vegetables.",
    "region": "Vietnam"},
    {"name": "Bo Luc Lac",
    "description": "Vietnamese dish of seared beef cubes often served with rice and a lime dipping sauce.",
    "region": "Vietnam"},
    {"name": "Cha Ca",
    "description": "A Hanoi specialty featuring grilled fish marinated in turmeric, served with vermicelli noodles and herbs.",
    "region": "Vietnam"},

    # Malaysia
    {"name": "Nasi Lemak",
    "description": "A Malaysian dish of fragrant rice cooked in coconut milk, often served with sambal, peanuts, and anchovies.",
    "region": "Malaysia"},
    {"name": "Roti Canai",
    "description": "Flaky and crispy Malaysian flatbread served with curry or dhal for dipping.",
    "region": "Malaysia"},
    {"name": "Laksa",
    "description": "A spicy noodle soup often made with coconut curry broth, seafood or meat, and various toppings.",
    "region": "Malaysia"},
    {"name": "Rendang",
    "description": "A rich and spicy Indonesian meat stew often enjoyed in Malaysia, made with coconut milk and a mix of spices.",
    "region": "Malaysia"},
    {"name": "Satay",
    "description": "Grilled skewers of meat (often chicken or beef) served with peanut sauce and rice cakes.",
    "region": "Malaysia"},
    {"name": "Char Kway Teow",
    "description": "Stir-fried flat rice noodles with shrimp, eggs, Chinese sausage, and bean sprouts.",
    "region": "Malaysia"},
    {"name": "Hainanese Chicken Rice",
    "description": "A Malaysian dish of poached chicken and fragrant rice cooked with chicken broth and aromatics.",
    "region": "Malaysia"},
    {"name": "Mee Goreng",
    "description": "Spicy stir-fried noodles often made with egg, shrimp, tofu, and vegetables.",
    "region": "Malaysia"},
    {"name": "Rojak",
    "description": "A Malaysian salad featuring a mix of fruits, vegetables, and fried dough fritters, often dressed in a spicy sauce.",
    "region": "Malaysia"},
    {"name": "Apam Balik",
    "description": "Malaysian pancake filled with crushed peanuts, sweet corn, and sugar.",
    "region": "Malaysia"},

    # Middle Eastern
    {"name": "Hummus",
    "description": "A popular Middle Eastern dip made from blended chickpeas, tahini, olive oil, and lemon juice.",
    "region": "Middle Eastern"},
    {"name": "Falafel",
    "description": "Deep-fried chickpea or fava bean patties often served in pita pockets or on a plate.",
    "region": "Middle Eastern"},
    {"name": "Shawarma",
    "description": "Thinly sliced meat (often lamb, beef, or chicken) wrapped in pita bread and topped with vegetables and sauces.",
    "region": "Middle Eastern"},
    {"name": "Baba Ghanoush",
    "description": "A smoky Middle Eastern dip made from roasted eggplants, tahini, garlic, and lemon juice.",
    "region": "Middle Eastern"},
    {"name": "Tabbouleh",
    "description": "A Lebanese salad made with finely chopped parsley, tomatoes, mint, onion, and bulgur.",
    "region": "Middle Eastern"},
    {"name": "Moutabal",
    "description": "A creamy Middle Eastern dip similar to baba ghanoush, but made with roasted eggplant and yogurt.",
    "region": "Middle Eastern"},
    {"name": "Kibbeh",
    "description": "A Levantine dish made from bulgur, minced onions, and ground meat (often lamb), shaped into balls or patties and fried.",
    "region": "Middle Eastern"},
    {"name": "Lamb Kofta",
    "description": "Spiced ground lamb or beef formed into meatballs or skewers and grilled or roasted.",
    "region": "Middle Eastern"},
    {"name": "Fattoush",
    "description": "A Middle Eastern salad made with mixed greens, vegetables, toasted pita bread, and sumac.",
    "region": "Middle Eastern"},
    {"name": "Mujadara",
    "description": "A Lebanese dish made from lentils, rice, and caramelized onions.",
    "region": "Middle Eastern"},

    # Morocco
    {"name": "Tagine",
    "description": "A slow-cooked Moroccan stew made in a clay pot, often featuring a mix of meats, vegetables, and aromatic spices.",
    "region": "Morocco"},
    {"name": "Couscous",
    "description": "A North African dish made from steamed and fluffed semolina grains, often served with stewed meats and vegetables.",
    "region": "Morocco"},
    {"name": "Harira",
    "description": "A Moroccan soup often served during Ramadan, made with tomatoes, lentils, chickpeas, and spices.",
    "region": "Morocco"},
    {"name": "Pastilla",
    "description": "A Moroccan savory pie made with layers of thin pastry, spiced meat (often pigeon), and almonds.",
    "region": "Morocco"},
    {"name": "Mechoui",
    "description": "A Moroccan dish of slow-roasted whole lamb, often prepared for festive occasions.",
    "region": "Morocco"},
    {"name": "Zaalouk",
    "description": "A Moroccan salad made from cooked eggplant, tomatoes, and a mixture of spices.",
    "region": "Morocco"},
    {"name": "Msemen",
    "description": "Moroccan square-shaped pancakes often enjoyed for breakfast or as a snack.",
    "region": "Morocco"},
    {"name": "Harcha",
    "description": "Moroccan semolina flatbread often served with butter, honey, or cheese.",
    "region": "Morocco"},
    {"name": "Chermoula",
    "description": "A Moroccan marinade and sauce made from herbs, spices, lemon, and oil, often used with fish or seafood.",
    "region": "Morocco"},
    {"name": "Baghrir",
    "description": "Moroccan crepes known as 'thousand-hole' pancakes due to their porous texture.",
    "region": "Morocco"},

    # Ethiopia
    {"name": "Doro Wat",
    "description": "Ethiopian spicy chicken stew made with berbere spice blend and served with injera (flatbread).",
    "region": "Ethiopia"},
    {"name": "Injera",
    "description": "Spongy Ethiopian flatbread made from teff flour, often used to scoop up stews and salads.",
    "region": "Ethiopia"},
    {"name": "Kitfo",
    "description": "A traditional Ethiopian dish made from raw minced beef, seasoned with spices and often served with injera.",
    "region": "Ethiopia"},
    {"name": "Tibs",
    "description": "Ethiopian dish made with grilled or sautéed meat, often served with injera or bread.",
    "region": "Ethiopia"},
    {"name": "Shiro",
    "description": "Ethiopian stew made from ground chickpeas or lentils cooked with spices, often served with injera.",
    "region": "Ethiopia"},
    {"name": "Tikil Gomen",
    "description": "Ethiopian dish of spiced cabbage, carrots, and potatoes cooked with turmeric and other spices.",
    "region": "Ethiopia"},
    {"name": "Berbere",
    "description": "A fiery Ethiopian spice blend often used in stews and sauces.",
    "region": "Ethiopia"},
    {"name": "Ayibe",
    "description": "Ethiopian cheese made from cottage cheese or ricotta, often served with injera and stews.",
    "region": "Ethiopia"},
    {"name": "Firfir",
    "description": "A traditional Ethiopian breakfast dish made from torn injera soaked in a spicy sauce.",
    "region": "Ethiopia"},
    {"name": "Tej",
    "description": "Ethiopian honey wine made from fermented honey and a special type of hops called 'gesho.'",
    "region": "Ethiopia"},

    # Nigeria
    {"name": "Jollof Rice",
    "description": "A West African rice dish cooked with tomatoes, peppers, onions, and various spices.",
    "region": "Nigeria"},
    {"name": "Pounded Yam and Egusi Soup",
    "description": "A Nigerian dish featuring pounded yam served with a thick soup made from melon seeds, vegetables, and sometimes meat.",
    "region": "Nigeria"},
    {"name": "Suya",
    "description": "Nigerian street food of grilled skewered meat coated in a spicy peanut mixture.",
    "region": "Nigeria"},
    {"name": "Akara",
    "description": "Nigerian bean fritters made from black-eyed peas, onions, and spices.",
    "region": "Nigeria"},
    {"name": "Efo Riro",
    "description": "Nigerian vegetable soup made with spinach, meat, fish, and assorted spices.",
    "region": "Nigeria"},
    {"name": "Moi Moi",
    "description": "Nigerian steamed bean pudding made from grounded peeled beans, onions, and peppers.",
    "region": "Nigeria"},
    {"name": "Egusi Soup",
    "description": "Nigerian soup made with ground melon seeds, leafy vegetables, and spices.",
    "region": "Nigeria"},
    {"name": "Boli",
    "description": "Nigerian grilled plantains, often served with spicy pepper sauce.",
    "region": "Nigeria"},
    {"name": "Ogbono Soup",
    "description": "Nigerian soup made with ground ogbono seeds, vegetables, and meat.",
    "region": "Nigeria"},
    {"name": "Fufu and Soup",
    "description": "A popular Nigerian dish featuring fufu (starchy side) served with various soups.",
    "region": "Nigeria"},

    # South Africa
    {"name": "Bobotie",
    "description": "A spiced minced meat dish with an egg-based topping, often served with rice and chutney.",
    "region": "South Africa"},
    {"name": "Biltong",
    "description": "Dried and cured meat often enjoyed as a snack in South Africa.",
    "region": "South Africa"},
    {"name": "Boerewors",
    "description": "Traditional South African sausage made from a mixture of meats and spices.",
    "region": "South Africa"},
    {"name": "Sosaties",
    "description": "South African skewered and marinated meat, often served at braais (barbecues).",
    "region": "South Africa"},
    {"name": "Chakalaka",
    "description": "South African spicy vegetable relish often served with bread, rice, or meat.",
    "region": "South Africa"},
    {"name": "Malva Pudding",
    "description": "South African dessert made with apricot jam and served warm with custard or ice cream.",
    "region": "South Africa"},
    {"name": "Potjiekos",
    "description": "Traditional South African stew slow-cooked in a three-legged cast-iron pot.",
    "region": "South Africa"},
    {"name": "Vetkoek",
    "description": "South African fried dough bread often served with savory or sweet fillings.",
    "region": "South Africa"},
    {"name": "Koeksisters",
    "description": "South African sweet treats made from fried dough soaked in syrup.",
    "region": "South Africa"},
    {"name": "Umngqusho",
    "description": "South African dish made from samp and beans, often served with meat or vegetables.",
    "region": "South Africa"},

    # United States
    {"name": "Burger",
    "description": "A classic American sandwich made with a ground meat patty served in a bun with various toppings.",
    "region": "United States"},
    {"name": "Hot Dog",
    "description": "A quintessential American street food made with a cooked sausage served in a sliced bun.",
    "region": "United States"},
    {"name": "Barbecue Ribs",
    "description": "Slow-cooked and grilled meat ribs slathered in barbecue sauce.",
    "region": "United States"},
    {"name": "Macaroni and Cheese",
    "description": "An American comfort food dish made with cooked macaroni pasta and a cheesy sauce.",
    "region": "United States"},
    {"name": "Clam Chowder",
    "description": "A creamy soup made with clams, potatoes, onions, and often celery and bacon.",
    "region": "United States"},
    {"name": "Apple Pie",
    "description": "A classic American dessert with a flaky pie crust and a filling made from sliced apples and spices.",
    "region": "United States"},
    {"name": "Buffalo Wings",
    "description": "Deep-fried chicken wings coated in a spicy buffalo sauce, often served with celery and blue cheese dressing.",
    "region": "United States"},
    {"name": "Peanut Butter and Jelly Sandwich",
    "description": "A simple sandwich made with peanut butter and fruit jelly or jam, often enjoyed by children.",
    "region": "United States"},
    {"name": "Cornbread",
    "description": "A Southern American bread made from cornmeal, often served as a side dish.",
    "region": "United States"},
    {"name": "New York-style Pizza",
    "description": "Large, thin-crust pizza slices often folded and eaten by hand.",
    "region": "United States"},

    # Canada
    {"name": "Poutine",
    "description": "A Canadian dish featuring fries topped with cheese curds and gravy.",
    "region": "Canada"},
    {"name": "Tourtière",
    "description": "A traditional Canadian meat pie often made with minced pork or a mixture of meats.",
    "region": "Canada"},
    {"name": "BeaverTails",
    "description": "A Canadian fried pastry often topped with various sweet toppings.",
    "region": "Canada"},
    {"name": "Nanaimo Bars",
    "description": "A Canadian dessert bar made with a layered mixture of crumbly cookie base, custard-flavored middle, and chocolate topping.",
    "region": "Canada"},
    {"name": "Peameal Bacon Sandwich",
    "description": "A sandwich made with peameal bacon (back bacon), often served on a bun with various toppings.",
    "region": "Canada"},
    {"name": "Butter Tart",
    "description": "A classic Canadian dessert tart made with a filling of butter, sugar, and eggs.",
    "region": "Canada"},
    {"name": "Bannock",
    "description": "A type of flatbread often associated with Indigenous cuisine in Canada.",
    "region": "Canada"},
    {"name": "Maple Syrup Pie",
    "description": "A sweet pie made with maple syrup, a quintessential Canadian ingredient.",
    "region": "Canada"},
    {"name": "Kraft Dinner (KD)",
    "description": "A Canadian brand of packaged macaroni and cheese, often considered a comfort food.",
    "region": "Canada"},
    {"name": "Smoked Meat Sandwich",
    "description": "A Canadian deli sandwich made with smoked meat (similar to pastrami) served on rye bread.",
    "region": "Canada"},

    # Australia
    {"name": "Meat Pie",
    "description": "A popular Australian savory pie filled with minced meat and gravy.",
    "region": "Australia"},
    {"name": "Vegemite Toast",
    "description": "A classic Australian breakfast featuring toast spread with Vegemite, a savory yeast extract spread.",
    "region": "Australia"},
    {"name": "Pavlova",
    "description": "An iconic Australian dessert consisting of a meringue base topped with whipped cream and fresh fruits.",
    "region": "Australia"},
    {"name": "Fish and Chips",
    "description": "A classic Australian takeaway dish featuring battered and deep-fried fish with thick-cut potato fries.",
    "region": "Australia"},
    {"name": "Anzac Biscuits",
    "description": "Australian cookies made from rolled oats, coconut, and golden syrup, often associated with Anzac Day.",
    "region": "Australia"},
    {"name": "Damper",
    "description": "An Australian soda bread often cooked over an open fire or campfire.",
    "region": "Australia"},
    {"name": "Chicken Parmigiana (Parma)",
    "description": "A popular Australian pub dish featuring breaded and fried chicken cutlet topped with tomato sauce and melted cheese.",
    "region": "Australia"},
    {"name": "Chiko Roll",
    "description": "An Australian deep-fried savory roll filled with meat and vegetables.",
    "region": "Australia"},
    {"name": "Tim Tam",
    "description": "A popular Australian chocolate biscuit made from layers of chocolate malted biscuit coated with chocolate.",
    "region": "Australia"},
    {"name": "Lamington",
    "description": "An Australian sponge cake coated in chocolate icing and desiccated coconut.",
    "region": "Australia"}
    ]


    # for ingredient in ingredients:
    #     for recipe in recipes:
    #         if ingredient.name.lower() in recipe.description.lower():
    #             food_association = FoodAssociation(ingredient_id=ingredient.id, recipe_id=recipe.id)
    #             session.add(food_association)
    # session.commit()


    # for recipe in recipes:
    #     for ingredient in ingredients:
    #         ingredient_name = ingredient.name
    #         for word in ingredient_name.split():
    #             if word.lower() in recipe.description.lower():
    #                 food_association = FoodAssociation(ingredient=ingredient, recipe=recipe)
    #                 session.add(food_association)
    # session.commit()


if __name__ == '__main__':
    engine = create_engine('sqlite:///lib/db/sql_food.db')
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    seed_database()
