"""Test

Revision ID: c558dea70902
Revises: adf664f819b5
Create Date: 2023-08-09 09:56:32.133981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c558dea70902'
down_revision = 'adf664f819b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('region', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'regions', ['region'], ['id'])
    op.drop_column('recipes', 'region_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('region_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'regions', ['region_id'], ['id'])
    op.drop_column('recipes', 'region')
    # ### end Alembic commands ###
